{$define UNIGUI_VCL} // Comment out this line to turn this project into an ISAPI module
(*
colar UNIGUI_VCL; antes do DEBUG dem DELPHI COMPILER

ai vai gerar EXE pra DEBUG
e DLL pra PRODUCAO

    aaaaaaaaaaaaaaa       aaaaaaaaaaaaaaa          aaaaaaaaaaa         aaaaaaaaaaaaa      aaaa    aaaa
    aaaaaaaaaaaaaaaaa     aaaaaaaaaaaaaaaaa      aaaaaaaaaaaaaaa     aaaaaaaaaaaaaaaa     aaaa    aaaa
    aaaa          aaaa    aaaa          aaaa    aaaa         aaaa    aaa          aaa     aaaa    aaaa
    aaaa          aaaa    aaaa          aaaa    aaaa         aaaa    aaa                  aaaa    aaaa
    aaaa          aaaa    aaaa          aaaa    aaaa         aaaa    aaa                  aaaa    aaaa
    aaaaaaaaaaaaaaa       aaaaaaaaaaaaaaa       aaaaaaaaaaaaaaaaa     aaaaaaaaaaaaaaa     aaaa    aaaa
    aaaaaaaaaaaaaaaaa     aaaaaaaaaaaaaaaaa     aaaaaaaaaaaaaaaaa      aaaaaaaaaaaaaaa    aaaa    aaaa
    aaaa          aaaa    aaaa          aaaa    aaaa         aaaa                  aaa    aaaa    aaaa
    aaaa          aaaa    aaaa          aaaa    aaaa         aaaa    aaa           aaa    aaaa    aaaa
    aaaaaaaaaaaaaaaaaa    aaaa          aaaa    aaaa         aaaa    aaaaaaaaaaaaaaaa     aaaa    aaaaaaaaaaaaaaaa
    aaaaaaaaaaaaaaaaa     aaaa          aaaa    aaaa         aaaa     aaaaaaaaaaaaaa      aaaa    aaaaaaaaaaaaaaaa
*)


{$ifndef UNIGUI_VCL}
library
{$else}
program
{$endif}
  RadCORE;



uses
  {$ifdef MSWINDOWS}
  uniGUIISAPI,
  {$endif }
  Forms,
  MidasLib,
  ServerModule in 'ServerModule.pas' {sm: TUniGUIServerModule},
  MainModule in 'MainModule.pas' {mm: TUniGUIMainModule},
  Main in 'Main.pas' {MainForm: TUniForm},
  uMenu_BASICS in 'formMENUS\uMenu_BASICS.pas',
  uMenu_TOOLS in 'formMENUS\uMenu_TOOLS.pas',
  uMenu_MOVEMENT in 'formMENUS\uMenu_MOVEMENT.pas',
  uMenu_OTHERS in 'formMENUS\uMenu_OTHERS.pas',
  uMenu_REPORTS in 'formMENUS\uMenu_REPORTS.pas',
  mkm_menus in 'formMENUS\mkm_menus.pas',
  mkm_func_web in 'FUNCTIONS\mkm_func_web.pas',
  Login in 'Login.pas' {frmLogin: TUniLoginForm},
  untFrmBase in 'frameBASE\untFrmBase.pas' {frmBase: TUniFrame},
  untFrmBaseCRUD in 'frameBase\untFrmBaseCRUD.pas' {frmBaseCRUD: TUniFrame},
  untCadCLIENTES in 'formMENUS\MENU_BASICS\untCadCLIENTES.pas' {frmCadCLIENTES: TUniFrame},
  str_func in 'FUNCTIONS\str_func.pas',
  untFrmLookUp in 'frameBASE\untFrmLookUp.pas' {frmLookUp: TUniForm},
  untCadFORNECEDORES in 'formMENUS\MENU_BASICS\untCadFORNECEDORES.pas' {frmCadFORNECEDORES: TUniFrame},
  untFrmInputBox in 'frameBASE\untFrmInputBox.pas' {frmInputBOX: TUniForm},
  untCadUSUARIOS in 'formMENUS\MENU_TOOLS\untCadUSUARIOS.pas' {frmCadUSUARIOS: TUniFrame},
  untFrmMessage in 'frameBASE\untFrmMessage.pas' {frmMessage: TUniForm},
  untFrmBaseCRUDDetail in 'frameBASE\untFrmBaseCRUDDetail.pas' {frmBaseCRUDDetail: TUniForm},
  untFrmBaseReportMenu in 'frameBASE\untFrmBaseReportMenu.pas' {frmBaseReportMenu: TUniFrame},
  untReportMenuClientes in 'formMENUS\MENU_REPORTS\untReportMenuClientes.pas' {frmReportMenuClientes: TUniFrame},
  untfrmBaseReportDefault in 'frameBASE\untfrmBaseReportDefault.pas' {frmBaseReportDefault: TUniForm},
  mkm_func_report in 'FUNCTIONS\mkm_func_report.pas',
  untReportClientesSimples in 'formMENUS\MENU_REPORTS\untReportClientesSimples.pas' {frmReportClientesSimples: TUniForm},
  untReportClientesCompleto in 'formMENUS\MENU_REPORTS\untReportClientesCompleto.pas' {frmReportClientesCompleto: TUniForm},
  uVersion in 'FUNCTIONS\uVersion.pas',
  untCadBASICS in 'formMENUS\MENU_BASICS\untCadBASICS.pas' {frmCadBASICS: TUniFrame},
  untCadCOMPRAS in 'formMENUS\MENU_MOVEMENT\untCadCOMPRAS.pas' {frmCadCOMPRAS: TUniFrame},
  untFrmBaseReport in 'frameBASE\untFrmBaseReport.pas' {frmBaseReport: TUniForm},
  untCadRECIBOS in 'formMENUS\MENU_MOVEMENT\untCadRECIBOS.pas' {frmCadRECIBOS: TUniFrame},
  untReportReciboSimples in 'formMENUS\MENU_REPORTS\untReportReciboSimples.pas' {frmReportReciboSimples: TUniForm},
  untCadCLIENTES_VEICULOS in 'formMENUS\MENU_BASICS\untCadCLIENTES_VEICULOS.pas' {frmCadCLIENTES_VEICULOS: TUniForm},
  untCadMOVCAIXA in 'formMENUS\MENU_MOVEMENT\untCadMOVCAIXA.pas' {frmCadMOVCAIXA: TUniFrame},
  untCadT040001 in 'formMENUS\MENU_BASICS\untCadT040001.pas' {frmCadT040001: TUniFrame},
  untFrmLookUp_Lite in 'frameBASE\untFrmLookUp_Lite.pas' {frmLookUp_Lite: TUniForm},
  untFrmFREEFRAME in 'formMENUS\MENU_BASICS\untFrmFREEFRAME.pas' {frmFreeFrame: TUniFrame},
  untFormBase in 'formBASE\untFormBase.pas' {formBase: TUniForm},
  untCadFERIADOS in 'formMENUS\MENU_BASICS\untCadFERIADOS.pas' {frmCadFERIADOS: TUniFrame},
  untFrmWEBCAM in 'formMENUS\MENU_TOOLS\untFrmWEBCAM.pas' {frmWEBCAM: TUniForm},
  untFrmTHEMES in 'formMENUS\MENU_TOOLS\untFrmTHEMES.pas' {frmThemes: TUniForm},
  untDM_RC in 'datamodules\untDM_RC.pas' {dm_rc: TDataModule},
  mkm_graphs in 'FUNCTIONS\mkm_graphs.pas',
  mkm_gridblock in 'FUNCTIONS\mkm_gridblock.pas',
  mkm_layout in 'FUNCTIONS\mkm_layout.pas',
  mkm_validate in 'FUNCTIONS\mkm_validate.pas',
  untFrmRCBLOCKS in 'formMENUS\MENU_BASICS\untFrmRCBLOCKS.pas' {frmRCBlocks: TUniFrame},
  untFrmDEMOWITHFORM in 'formMENUS\MENU_BASICS\untFrmDEMOWITHFORM.pas' {frmDEMOWithForm: TUniForm},
  untFrmDEMOWITHFORMMODAL in 'formMENUS\MENU_BASICS\untFrmDEMOWITHFORMMODAL.pas' {frmDEMOWithFormMODAL: TUniForm},
  untFrmRCRacing in 'formMENUS\MENU_BASICS\untFrmRCRacing.pas' {frmRCRACING: TUniFrame},
  mkm_anim in 'FUNCTIONS\mkm_anim.pas',
  mkm_translate in 'FUNCTIONS\mkm_translate.pas',
  untFrmTRANSLATE in 'formMENUS\MENU_TOOLS\untFrmTRANSLATE.pas' {frmTranslate: TUniForm},
  untFrmBasePDF in 'frameBASE\untFrmBasePDF.pas' {frmBasePDF: TUniForm},
  untFrmWIZARD in 'formMENUS\MENU_BASICS\untFrmWIZARD.pas' {frmWIZARD: TUniFrame},
  untFrmWIZARDDEMO in 'formMENUS\MENU_BASICS\untFrmWIZARDDEMO.pas' {frmWIZARDDEMO: TUniForm},
  uconsts in 'functions\uconsts.pas',
  mkm_email in 'FUNCTIONS\mkm_email.pas',
  untFrmFISHFACT in 'formMENUS\MENU_BASICS\untFrmFISHFACT.pas' {frmFishFact: TUniFrame},
  mkm_login in 'FUNCTIONS\mkm_login.pas',
  untCadCLIENTES_REVISOES in 'formMENUS\MENU_BASICS\untCadCLIENTES_REVISOES.pas' {frmCadCLIENTES_REVISOES: TUniForm},
  DelphiZXIngQRCode in 'FUNCTIONS\DelphiZXIngQRCode.pas',
  mkm_qrcode in 'FUNCTIONS\mkm_qrcode.pas',
  untCadTB_COMPOUNDPK in 'formMENUS\MENU_BASICS\untCadTB_COMPOUNDPK.pas' {frmCadTB_COMPOUNDPK: TUniFrame},
  untCadTITULOS in 'formMENUS\MENU_BASICS\untCadTITULOS.pas' {frmBaseTITULOS: TUniFrame},
  untCadRECEBER in 'formMENUS\MENU_MOVEMENT\untCadRECEBER.pas' {frmcadRECEBER: TUniFrame},
  mkm_procedures in 'functions\mkm_procedures.pas',
  mkm_funcoes in 'functions\mkm_funcoes.pas',
  untFrmPesquisa in 'frameBASE\untFrmPesquisa.pas' {frmPesquisa: TUniForm},
  untCadPAGAR in 'formMENUS\MENU_MOVEMENT\untCadPAGAR.pas' {frmcadPAGAR: TUniFrame},
  untCadBANCOS in 'formMENUS\MENU_MOVEMENT\untCadBANCOS.pas' {frmcadBANCOS: TUniFrame},
  mkm_regrasnegocio in 'regras\mkm_regrasnegocio.pas',
  untFrmCAIXADIARIO in 'formMENUS\MENU_MOVEMENT\untFrmCAIXADIARIO.pas' {frmCAIXADIARIO: TUniFrame},
  untFrmEXTRATOBANCARIO in 'formMENUS\MENU_MOVEMENT\untFrmEXTRATOBANCARIO.pas' {frmEXTRATOBANCARIO: TUniFrame},
  untFrmPLANOCONTASINDIVIDUAL in 'formMENUS\MENU_MOVEMENT\untFrmPLANOCONTASINDIVIDUAL.pas' {frmPLANOCONTASINDIVIDUAL: TUniFrame},
  untFrmPLANOCONTASANALITICO in 'formMENUS\MENU_MOVEMENT\untFrmPLANOCONTASANALITICO.pas' {frmPLANOCONTASANALITICO: TUniFrame},
  untFrmPLANOCONTASRESUMO in 'formMENUS\MENU_MOVEMENT\untFrmPLANOCONTASRESUMO.pas' {frmPLANOCONTASRESUMO: TUniFrame},
  untFrmBANCORESUMO in 'formMENUS\MENU_MOVEMENT\untFrmBANCORESUMO.pas' {frmBANCORESUMO: TUniFrame},
  untFrmBASEBAIXATITULOS in 'formMENUS\MENU_MOVEMENT\untFrmBASEBAIXATITULOS.pas' {frmBASEBAIXATITULOS: TUniFrame},
  untFrmMOVIMENTOMESTRE in 'formMENUS\MENU_MOVEMENT\untFrmMOVIMENTOMESTRE.pas' {frmMOVIMENTOMESTRE: TUniFrame},
  untFrmORCAMENTO in 'formMENUS\MENU_MOVEMENT\untFrmORCAMENTO.pas' {frmORCAMENTO: TUniFrame},
  untFrmPEDIDOS in 'formMENUS\MENU_MOVEMENT\untFrmPEDIDOS.pas' {frmPEDIDOS: TUniFrame},
  untFrmNOTAELETRONICA in 'formMENUS\MENU_MOVEMENT\untFrmNOTAELETRONICA.pas' {frmNOTAELETRONICA: TUniFrame},
  untFrmBAIXARECEBER in 'formMENUS\MENU_MOVEMENT\untFrmBAIXARECEBER.pas' {frmBAIXARECEBER: TUniFrame},
  untFrmBaixaTitulos in 'frameBASE\untFrmBaixaTitulos.pas' {frmBAIXATITULOS: TUniForm},
  untFrmBAIXAPAGAR in 'formMENUS\MENU_MOVEMENT\untFrmBAIXAPAGAR.pas' {frmBAIXAPAGAR: TUniFrame},
  untFrmPROTOCOLO in 'formMENUS\MENU_BASICS\untFrmPROTOCOLO.pas' {frmCADprotocolo: TUniFrame},
  mkm_dbfuncs in 'functions\mkm_dbfuncs.pas',
  mkm_dbcombobox in 'functions\mkm_dbcombobox.pas',
  untFormCRUDPROPRIO in 'formBASE\untFormCRUDPROPRIO.pas' {frmCRUDPROPRIO: TUniFrame},
  untCadCATEGORIA in 'formMENUS\MENU_BASICS\untCadCATEGORIA.pas' {frmCADCATEGORIA: TUniFrame},
  untCadPENEIRA in 'formMENUS\MENU_BASICS\untCadPENEIRA.pas' {frmCadPENEIRA: TUniFrame},
  untCadESPECIE in 'formMENUS\MENU_BASICS\untCadESPECIE.pas' {frmCADESPECIE: TUniFrame},
  untCadCULTIVAR in 'formMENUS\MENU_BASICS\untCadCULTIVAR.pas' {frmCADCULTIVAR: TUniFrame},
  untCadPRAGAS in 'formMENUS\MENU_BASICS\untCadPRAGAS.pas' {frmCADPRAGAS: TUniFrame},
  untCadBALANCAS in 'formMENUS\MENU_BASICS\untCadBALANCAS.pas' {frmCADBALANCAS: TUniFrame},
  untCadHISTORICO in 'formMENUS\MENU_BASICS\untCadHISTORICO.pas' {frmCADHISTORICO: TUniFrame},
  untCadCARTEIRA in 'formMENUS\MENU_BASICS\untCadCARTEIRA.pas' {frmCADCARTEIRA: TUniFrame},
  untCadCONDICOES in 'formMENUS\MENU_BASICS\untCadCONDICOES.pas' {frmCADCONDICOES: TUniFrame},
  untCadESCRITAS in 'formMENUS\MENU_BASICS\untCadESCRITAS.pas' {frmCADESCRITAS: TUniFrame},
  untCadPARAMETROSOPERACAO in 'formMENUS\MENU_BASICS\untCadPARAMETROSOPERACAO.pas' {frmCADPARAMETROSOPERACAO: TUniFrame},
  untCadPORTADORES in 'formMENUS\MENU_BASICS\untCadPORTADORES.pas' {frmCADPORTADORES: TUniFrame},
  untCadREGIAO in 'formMENUS\MENU_BASICS\untCadREGIAO.pas' {frmCADREGIAO: TUniFrame},
  untCadMEDIDAS in 'formMENUS\MENU_BASICS\untCadMEDIDAS.pas' {frmCADMEDIDAS: TUniFrame},
  untCadCENTROCUSTO in 'formMENUS\MENU_BASICS\untCadCENTROCUSTO.pas' {frmCADCENTROCUSTO: TUniFrame},
  untCadPLANOCONTAS in 'formMENUS\MENU_BASICS\untCadPLANOCONTAS.pas' {frmCADPLANOCONTAS: TUniFrame},
  untCadDOCUMENTOS in 'formMENUS\MENU_BASICS\untCadDOCUMENTOS.pas' {frmCADDOCUMENTOS: TUniFrame},
  untCadAPLICACAO in 'formMENUS\MENU_BASICS\untCadAPLICACAO.pas' {frmCADAPLICACAO: TUniFrame},
  untCadGRUPOS in 'formMENUS\MENU_BASICS\untCadGRUPOS.pas' {frmCADGRUPOS: TUniFrame},
  untCadOPERACOES in 'formMENUS\MENU_BASICS\untCadOPERACOES.pas' {frmCADOPERACOES: TUniFrame},
  untCadGERMINADOR in 'formMENUS\MENU_BASICS\untCadGERMINADOR.pas' {frmCADGERMINADOR: TUniFrame},
  untCadPROBABILIDADE in 'formMENUS\MENU_BASICS\untCadPROBABILIDADE.pas' {frmCADPROBABILIDADE: TUniFrame},
  untCadTOLERANCIA in 'formMENUS\MENU_BASICS\untCadTOLERANCIA.pas' {frmCADTOLERANCIA: TUniFrame},
  untCadGRUPOSESPECIE in 'formMENUS\MENU_BASICS\untCadGRUPOSESPECIE.pas' {frmCADGRUPOSESPECIE: TUniFrame},
  untDM_IMP in 'datamodules\untDM_IMP.pas' {dm_imp: TDataModule},
  unReportImpressao in 'formMENUS\MENU_REPORTS\unReportImpressao.pas' {unfImpressao: TUniForm},
  mkm_impressao in 'functions\mkm_impressao.pas',
  untCadLABORATORIO in 'formMENUS\MENU_BASICS\untCadLABORATORIO.pas' {frmCADLABORATORIO: TUniFrame},
  untCadRESPONSAVEL in 'formMENUS\MENU_BASICS\untCadRESPONSAVEL.pas' {frmCADRESPONSAVEL: TUniFrame},
  untCadSEMENTES in 'formMENUS\MENU_BASICS\untCadSEMENTES.pas' {frmCADSEMENTES: TUniFrame},
  untFrmProtocoloopcoes in 'frameBASE\untFrmProtocoloopcoes.pas' {frmProtocoloopcoes: TUniForm},
  untFrmRelatorioLevantamento in 'frameBASE\untFrmRelatorioLevantamento.pas' {FrmRelatorioLevantamento: TUniFrame},
  untFrmDEMONSTRATIVO in 'formMENUS\MENU_BASICS\untFrmDEMONSTRATIVO.pas' {frmDEMONSTRATIVO: TUniFrame},
  untFrmLaboratorioRAM in 'formMENUS\MENU_BASICS\untFrmLaboratorioRAM.pas' {frmLaboratorioRAM: TUniFrame},
  untFrmLaboratorioSEMRENASEM in 'formMENUS\MENU_BASICS\untFrmLaboratorioSEMRENASEM.pas' {frmSEMRENASEM: TUniFrame},
  untFrmLaboratorioRELATORIOENTRADAS in 'formMENUS\MENU_BASICS\untFrmLaboratorioRELATORIOENTRADAS.pas' {frmRELATORIOENTRADAS: TUniFrame},
  untFrmTELAGENERICA in 'frameBASE\untFrmTELAGENERICA.pas' {frmTELAGENERICA: TUniForm},
  untCadPESSOAS in 'formMENUS\MENU_BASICS\untCadPESSOAS.pas' {frmcadPESSOAS: TUniFrame},
  untFrmTransfereImportacao in 'frameBASE\untFrmTransfereImportacao.pas' {frmTransfereImportacao: TUniForm},
  untCadTRANSPORTES in 'formMENUS\MENU_BASICS\untCadTRANSPORTES.pas' {frmcadTRANSPORTES: TUniFrame},
  untcadFUNCIONARIOS in 'formMENUS\MENU_BASICS\untcadFUNCIONARIOS.pas' {frmcadFUNCIONARIOS: TUniFrame},
  untCadPRODUTOS in 'formMENUS\MENU_BASICS\untCadPRODUTOS.pas' {frmcadPRODUTOS: TUniFrame},
  untCadEMPRESAS in 'formMENUS\MENU_BASICS\untCadEMPRESAS.pas' {frmcadEMPRESAS: TUniFrame},
  untCadPONTOS in 'formMENUS\MENU_BASICS\untCadPONTOS.pas' {frmcadPONTOS: TUniFrame},
  untfrmSEFAZNOTA in 'frameBASE\untfrmSEFAZNOTA.pas' {frmSEFAZNOTA: TUniForm},
  mkm_relatorios in 'functions\mkm_relatorios.pas',
  untCadBATIDAMESTRE in 'formMENUS\MENU_BASICS\untCadBATIDAMESTRE.pas' {frmCADBATIDAMESTRE: TUniFrame},
  untfrmPesquisalote in 'frameBASE\untfrmPesquisalote.pas' {he: TUniForm},
  untfrmTelaproducaogenerica in 'frameBASE\untfrmTelaproducaogenerica.pas' {frmtelaproducaogenerica: TUniForm},
  untfrmDeclaracaoretirada in 'frameBASE\untfrmDeclaracaoretirada.pas' {frmdeclaracaoretirada: TUniForm},
  untFrmMANIFESTO in 'formMENUS\MENU_MOVEMENT\untFrmMANIFESTO.pas' {frmMANIFESTO: TUniFrame},
  untfrmSEFAZMANIFESTO in 'frameBASE\untfrmSEFAZMANIFESTO.pas' {frmSEFAZMANIFESTO: TUniForm},
  untfrmImpressaoFinanceiro in 'frameBASE\untfrmImpressaoFinanceiro.pas' {frmimpressaofinanceiro: TUniForm},
  untfrmRELATORIOS in 'formMENUS\MENU_BASICS\untfrmRELATORIOS.pas' {frmRELATORIOS: TUniForm},
  untFrmRELATORIOBASE in 'frameBASE\untFrmRELATORIOBASE.pas' {frmRELATORIOBASE: TUniForm},
  untFrmMANUTENCAOLOTE in 'frameBASE\untFrmMANUTENCAOLOTE.pas' {frmMANUTENCAOLOTE: TUniForm},
  untFrmDETALHESITENSNOTA in 'frameBASE\untFrmDETALHESITENSNOTA.pas' {frmDETALHESITENSNOTA: TUniForm},
  untFrmTRANSPORTADORAMOVIMENTO in 'frameBASE\untFrmTRANSPORTADORAMOVIMENTO.pas' {frmTRANPORTADORAMOVIMENTO: TUniForm},
  untFrmRELATORIO_LOTE in 'formMENUS\MENU_BASICS\untFrmRELATORIO_LOTE.pas' {frmRELATORIO_LOTE: TUniForm},
  untCadRASTREIO in 'formMENUS\MENU_TOOLS\untCadRASTREIO.pas' {frmCADRASTREIO: TUniFrame},
  untFrmPesquisaItensestoque in 'frameBASE\untFrmPesquisaItensestoque.pas' {frmpesquisaitensestoque: TUniForm},
  untFrmFLUXOCAIXA in 'formMENUS\MENU_MOVEMENT\untFrmFLUXOCAIXA.pas' {frmFLUXOCAIXA: TUniFrame},
  untCadBENEFICIAMENTO in 'formMENUS\MENU_BASICS\untCadBENEFICIAMENTO.pas' {frmCADBENEFICIAMENTO: TUniFrame},
  untFrmDETALHESBENEFICIAMENTO in 'frameBASE\untFrmDETALHESBENEFICIAMENTO.pas' {frmDETALHESBENEFICIAMENTO: TUniForm},
  untcadMENUSISTEMA in 'formMENUS\MENU_TOOLS\untcadMENUSISTEMA.pas' {frmcadMENUSISTEMA: TUniFrame},
  untFrmNOTAENTRADA in 'formMENUS\MENU_MOVEMENT\untFrmNOTAENTRADA.pas' {frmNOTAENTRADA: TUniFrame},
  untFrmRELATORIO_IMPOSTOCONTABILIDADE in 'formMENUS\MENU_BASICS\untFrmRELATORIO_IMPOSTOCONTABILIDADE.pas' {frmRELATORIO_IMPOSTOCONTABILIDADE: TUniForm},
  untFrmRELATORIO_VENDASDETALHES in 'formMENUS\MENU_BASICS\untFrmRELATORIO_VENDASDETALHES.pas' {frmRELATORIO_VENDASDETALHADA: TUniForm},
  untFrmDASHBOARDFINANCEIRO in 'frameBASE\untFrmDASHBOARDFINANCEIRO.pas' {frmDASHBOARDFINANCEIRO: TUniFrame},
  mkm_graficos in 'functions\mkm_graficos.pas',
  untFrmCURVAABCPESSOA in 'formMENUS\MENU_BASICS\untFrmCURVAABCPESSOA.pas' {frmCURVAABCPESSOA: TUniFrame},
  untFrmRELATORIO_HISTORICOSEMENTE in 'formMENUS\MENU_BASICS\untFrmRELATORIO_HISTORICOSEMENTE.pas' {frmRELATORIO_HISTORICOSEMENTE: TUniForm},
  untFrmRELATORIO_SALDOBENENOTAS in 'formMENUS\MENU_BASICS\untFrmRELATORIO_SALDOBENENOTAS.pas' {frmSALDOBENEFICIAMENTO: TUniForm},
  untCadCAMPO in 'formMENUS\MENU_BASICS\untCadCAMPO.pas' {frmcadCAMPO: TUniFrame},
  untFrmHISTORICOBENENOTA in 'formMENUS\MENU_MOVEMENT\untFrmHISTORICOBENENOTA.pas' {frmHISTORICOBENENOTA: TUniFrame},
  untFrmHISTORICOCAMPO in 'formMENUS\MENU_BASICS\untFrmHISTORICOCAMPO.pas' {frmHISTORICOCAMPO: TUniFrame},
  untFrmTERMOADITIVO in 'formMENUS\MENU_BASICS\untFrmTERMOADITIVO.pas' {frmTEMOADITIVO: TUniForm},
  untFrmCONSULTACNPJ in 'frameBASE\untFrmCONSULTACNPJ.pas' {frmCONSULTACNPJ: TUniForm},
  untFrmRELATORIOCONTROLEITENSEF in 'frameBASE\untFrmRELATORIOCONTROLEITENSEF.pas' {frmRELATORIOCONTROLEITENSEF: TUniForm},
  untFrmGRAFICO_COMPARATIVOFAT in 'frameBASE\untFrmGRAFICO_COMPARATIVOFAT.pas' {frmGRAFICO_COMPARATIVOFAT: TUniFrame},
  untFrmGRAFICO_COMPARATIVOANUALFAT in 'frameBASE\untFrmGRAFICO_COMPARATIVOANUALFAT.pas' {frmGRAFICO_COMPARATIVOANUALFAT: TUniFrame},
  untFrmSEMENTEBAS in 'frameBASE\untFrmSEMENTEBAS.pas' {frmSEMENTEBAS: TUniForm},
  untFrmSPEDEFD in 'frameBASE\untFrmSPEDEFD.pas' {frmSPEDEFD: TUniFrame},
  mkm_spedfiscalefd in 'functions\mkm_spedfiscalefd.pas',
  untCadTABELAICMS in 'formMENUS\MENU_BASICS\untCadTABELAICMS.pas' {frmcadTABELAICMS: TUniFrame},
  untfrmRELATORIOVENVENDEDOR in 'formMENUS\MENU_BASICS\untfrmRELATORIOVENVENDEDOR.pas' {frmRELATORIOVENVENDEDOR: TUniForm},
  untFrmSPEDPISCOFINS in 'frameBASE\untFrmSPEDPISCOFINS.pas' {frmSPEDPISCOFINS: TUniFrame},
  mkm_spedpiscofins in 'functions\mkm_spedpiscofins.pas',
  untFrmCADENTREGAS in 'frameBASE\untFrmCADENTREGAS.pas' {frmCADENTREGAS: TUniForm},
  untFrmRELACAOENTREGAS in 'frameBASE\untFrmRELACAOENTREGAS.pas' {frmRELACAOENTREGAS: TUniForm},
  untFrmARQUIVOXML in 'frameBASE\untFrmARQUIVOXML.pas' {frmARQUIVOXML: TUniFrame},
  untCadROMANEIO in 'formMENUS\MENU_MOVEMENT\untCadROMANEIO.pas' {frmcadROMANEIO: TUniFrame},
  untFrmCHEQUES in 'formMENUS\MENU_BASICS\untFrmCHEQUES.pas' {frmCADCHEQUES: TUniFrame},
  untFrmCADCHEQUES_HISTORICO in 'frameBASE\untFrmCADCHEQUES_HISTORICO.pas' {frmcadcheques_historico: TUniForm},
  untFrmCADCHEQUEMOVIMENTO in 'frameBASE\untFrmCADCHEQUEMOVIMENTO.pas' {frmCADCHEQUESMOVIMENTO: TUniForm},
  untFrmLIXEIRA in 'frameBASE\untFrmLIXEIRA.pas' {frmLIXEIRA: TUniForm},
  untCadBARRACAO in 'formMENUS\MENU_BASICS\untCadBARRACAO.pas' {frmcadBARRACAO: TUniFrame},
  untCadLOTEINTERNO in 'formMENUS\MENU_BASICS\untCadLOTEINTERNO.pas' {frmcadLOTEINTERNO: TUniFrame},
  untCadPRODUCAOINTERNA in 'formMENUS\MENU_BASICS\untCadPRODUCAOINTERNA.pas' {frmcadPRODUCAOINTERNA: TUniFrame},
  untFrmPesquisaloteinterno in 'frameBASE\untFrmPesquisaloteinterno.pas' {FrmPesquisaloteinterno: TUniForm},
  untCadMANUTENCAOLOTE_INTERNO in 'formMENUS\MENU_BASICS\untCadMANUTENCAOLOTE_INTERNO.pas' {frmcadMANUTENCAOLOTE_INTERNO: TUniFrame},
  untFrmRELACAOLOTEINTERNO in 'frameBASE\untFrmRELACAOLOTEINTERNO.pas' {frmRELACAOLOTEINTERNO: TUniForm},
  untFrmCTEENTRADA in 'formMENUS\MENU_BASICS\untFrmCTEENTRADA.pas' {frmCTEENTRADA: TUniFrame},
  untFrmSTATUSMOVIMENTO in 'frameBASE\untFrmSTATUSMOVIMENTO.pas' {frmSTATUSMOVIMENTO: TUniForm},
  untFrmBLOQUEIOSISTEMA in 'frameBASE\untFrmBLOQUEIOSISTEMA.pas' {frmBLOQUEIOSISTEMA: TUniForm},
  untfrmTELAAVISOSISTEMA in 'frameBASE\untfrmTELAAVISOSISTEMA.pas' {frmTELAAVISOSISTEMA: TUniForm},
  untCadMARCA in 'formMENUS\MENU_BASICS\untCadMARCA.pas' {frmcadMARCA: TUniFrame},
  untFrmEXTRATOFINANCEIROPESSOA in 'formMENUS\MENU_MOVEMENT\untFrmEXTRATOFINANCEIROPESSOA.pas' {frmEXTRATOFINANCEIROPESSOA: TUniFrame},
  untCadSOLICITACAO in 'formMENUS\MENU_BASICS\untCadSOLICITACAO.pas' {frmCADSOLICITACAO: TUniFrame},
  untFrmMENURTASSINATURA in 'formMENUS\MENU_TOOLS\untFrmMENURTASSINATURA.pas' {frmMENURTASSINATURA: TUniForm},
  untFrmCARDASSINATURART in 'formMENUS\MENU_MOVEMENT\untFrmCARDASSINATURART.pas' {frmCARDASSINATURART: TUniFrame},
  untFrmTERMOCOLETA in 'frameBASE\untFrmTERMOCOLETA.pas' {frmTERMOCOLETA: TUniForm},
  untFrmIMPRESSAOENTREGAPARCIAL in 'frameBASE\untFrmIMPRESSAOENTREGAPARCIAL.pas' {FrmIMPRESSAOENTREGAPARCIAL: TUniForm},
  untFrmCONSULTAKARDEXLOTE in 'formMENUS\MENU_MOVEMENT\untFrmCONSULTAKARDEXLOTE.pas' {frmCONSULTAKARDEXLOTE: TUniFrame},
  untFrmCONSULTAKARDEXPRODUTO in 'formMENUS\MENU_BASICS\untFrmCONSULTAKARDEXPRODUTO.pas' {frmCONSULTAKARDEXPRODUTO: TUniFrame},
  untFrmBLOQUEIOPESSOA in 'frameBASE\untFrmBLOQUEIOPESSOA.pas' {frmBLOQUEIOPESSOA: TUniForm},
  untFrmTELADETALHESPRODUCAODLOTE in 'frameBASE\untFrmTELADETALHESPRODUCAODLOTE.pas' {FrmTELADETALHESPRODUCAODLOTE: TUniForm},
  untFrmFICHA in 'frameBASE\untFrmFICHA.pas' {frmFICHA: TUniForm},
  untFrmRELATORIOPERIODOPRODUTO in 'formMENUS\MENU_BASICS\untFrmRELATORIOPERIODOPRODUTO.pas' {FrmRELATORIOPERIODOPRODUTO: TUniForm},
  untFrmRELATORIOHISTORICOSEMENTESINTETICO in 'formMENUS\MENU_BASICS\untFrmRELATORIOHISTORICOSEMENTESINTETICO.pas' {FrmRELATORIOHISTORICOSEMENTESINTETICO: TUniForm},
  untFrmSALDOPRODUTONOTAS in 'formMENUS\MENU_BASICS\untFrmSALDOPRODUTONOTAS.pas' {frmSALDOPRODUTONOTAS: TUniForm},
  untFrmENVIOEMAIL in 'frameBASE\untFrmENVIOEMAIL.pas' {FrmENVIOEMAIL: TUniForm},
  untfrmENTREGALOTE in 'frameBASE\untfrmENTREGALOTE.pas' {frmENTREGALOTE: TUniForm},
  untCadCIDADES in 'formMENUS\MENU_BASICS\untCadCIDADES.pas' {frmcadCIDADES: TUniFrame},
  untFrmRELATORIOSALDOEFEP in 'formMENUS\MENU_BASICS\untFrmRELATORIOSALDOEFEP.pas' {frmRELATORIOSALDOEFEP: TUniForm},
  untCadCUSTO_LOTEINTERNO in 'formMENUS\MENU_BASICS\untCadCUSTO_LOTEINTERNO.pas' {frmCadCUSTO_LOTEINTERNO: TUniFrame},
  untFrmCUSTOPRODUCAO in 'frameBASE\untFrmCUSTOPRODUCAO.pas' {frmCUSTOPRODUCAO: TUniForm},
  untFrmCRESCIMENTOFATEMPRESA in 'formMENUS\MENU_BASICS\untFrmCRESCIMENTOFATEMPRESA.pas' {FrmCRESCIMENTOFATEMPRESA: TUniForm},
  untFrmCOMISSAOBAIXAEFETUADA in 'formMENUS\MENU_BASICS\untFrmCOMISSAOBAIXAEFETUADA.pas' {frmCOMISSAOBAIXAEFETUADA: TUniForm},
  untFrmPREVISAOCOMISSAO in 'formMENUS\MENU_BASICS\untFrmPREVISAOCOMISSAO.pas' {frmPREVISAOCOMISSAO: TUniForm},
  untCadEXTRATO_COMISSAO in 'formMENUS\MENU_BASICS\untCadEXTRATO_COMISSAO.pas' {frmCadEXTRATO_COMISSAO: TUniFrame},
  untFrmFICHAANALISTA in 'frameBASE\untFrmFICHAANALISTA.pas' {frmFICHAANALISTA: TUniForm},
  untFrmANEXOTITULOS in 'frameBASE\untFrmANEXOTITULOS.pas' {frmCADANEXOTITULOS: TUniForm},
  untFrmTELAMOVIMENTOBOLETOS in 'regras\untFrmTELAMOVIMENTOBOLETOS.pas' {frmTELAMOVIMENTOBOLETOS: TUniForm},
  untFrmGERARREMESSABANCARIA in 'regras\untFrmGERARREMESSABANCARIA.pas' {frmGERARREMESSABANCARIA: TUniFrame},
  untFrmGERARRETORNOBANCARIO in 'regras\untFrmGERARRETORNOBANCARIO.pas' {frmGERARRETORNOBANCARIO: TUniFrame},
  untFrmCURVAABCPRODUTOS in 'formMENUS\MENU_BASICS\untFrmCURVAABCPRODUTOS.pas' {FrmCURVAABCPRODUTOS: TUniFrame},
  untFrmRELATORIOCOMPRASPRODUTO in 'formMENUS\MENU_BASICS\untFrmRELATORIOCOMPRASPRODUTO.pas' {FrmRELATORIOCOMPRASPRODUTO: TUniForm},
//  untFrmPORTALFORRAGEIRA in '..\Sisgraos_portal_laboratorio\untFrmPORTALFORRAGEIRA.pas' {frmPORTALFORRAGEIRA: TUniFrame},
  untfrmTELAAVISOMSG in 'frameBASE\untfrmTELAAVISOMSG.pas' {frmTELAAVISOMSG: TUniForm},
  uMsgInfo in 'frameBASE\uMsgInfo.pas',
  uNFE in 'classe notas\uNFE.pas';

{$R *.res}

{$ifndef UNIGUI_VCL}
exports
  GetExtensionVersion,
  HttpExtensionProc,
  TerminateExtension;
{$endif}

begin
{$ifdef UNIGUI_VCL}
  ReportMemoryLeaksOnShutdown := True;
  Application.Initialize;
  Tsm.Create(Application);
  Application.Run;
{$endif}
end.

